name: Test
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Coookiecutter
        run: python3 -m pip install --user cookiecutter
      - name: Install Poetry
        run: pipx install poetry
      - name: Run tests
        run: cookiecutter --no-input .